const express = require('express');
const router = express.Router();
const axios = require('axios');
const InteropClinicalResource = require('../models/ClinicalResource');
const { dispatchWebhookEvent } = require('../services/webhookEngine');

const AI_SERVICE_URL = process.env.AI_SERVICE_URL || 'http://localhost:8001';

// POST /api/v1/triage
router.post('/', async (req, res) => {
  const orgId = req.user ? req.user.org_id : 'org_apollo_metro';
  const { patientId, symptoms, vitals } = req.body;

  try {
    let aiAssessment = null;

    // Call meditrack_ai service if accessible, or generate clinical rule-based triage assessment
    try {
      const response = await axios.post(`${AI_SERVICE_URL}/api/triage`, {
        symptoms,
        vitals
      }, { timeout: 3000 });
      aiAssessment = response.data;
    } catch (err) {
      // Fallback rule-based triage assessment
      const hasSevereSymptom = (symptoms || '').toLowerCase().match(/chest pain|difficulty breathing|unconscious|severe bleeding/);
      aiAssessment = {
        urgency: hasSevereSymptom ? 'EMERGENCY' : 'URGENT',
        riskCategory: hasSevereSymptom ? 'High Risk' : 'Moderate Risk',
        recommendedSpecialty: hasSevereSymptom ? 'Emergency Cardiology' : 'General Internal Medicine',
        summary: `AI Assessment for symptoms: "${symptoms || 'General discomfort'}". Preliminary recommendation.`
      };
    }

    // Map AI Triage to FHIR CarePlan resource (Explicitly Tagged as AI-Generated Assessment)
    const fhirId = `CarePlan-AI-${Date.now()}`;
    const fhirCarePlan = {
      resourceType: 'CarePlan',
      id: fhirId,
      status: 'draft',
      intent: 'proposal',
      category: [
        {
          coding: [
            {
              system: 'https://meditrack.org/fhir/CodeSystem/provenance-type',
              code: 'AI-GENERATED-ASSESSMENT',
              display: 'AI-Generated Assessment (Requires Clinician Review)'
            }
          ],
          text: 'AI Clinical Triage Assessment'
        }
      ],
      title: `[AI PROVISIONAL ASSESSMENT] ${aiAssessment.riskCategory}`,
      description: `${aiAssessment.summary}. NOTE: THIS IS AN AI-GENERATED SUGGESTION AND NOT A CLINICIAN-CONFIRMED DIAGNOSIS.`,
      subject: {
        reference: `Patient/${patientId || 'unknown'}`
      },
      created: new Date().toISOString(),
      activity: [
        {
          detail: {
            kind: 'ServiceRequest',
            code: {
              text: `Recommended Specialty: ${aiAssessment.recommendedSpecialty}`
            },
            status: 'in-progress'
          }
        }
      ]
    };

    const record = await InteropClinicalResource.create({
      organizationId: orgId,
      resourceType: 'CarePlan',
      fhirId: fhirId,
      patientId: patientId || 'unknown',
      status: 'draft',
      resource: fhirCarePlan
    });

    dispatchWebhookEvent(orgId, 'triage.completed', {
      patientId,
      triageId: fhirId,
      provenance: 'AI-GENERATED-ASSESSMENT',
      urgency: aiAssessment.urgency,
      carePlan: fhirCarePlan
    });

    res.status(201).json({
      success: true,
      provenance: 'AI-GENERATED-ASSESSMENT',
      clinicianConfirmed: false,
      disclaimer: 'This assessment was generated by AI and must be reviewed by a licensed clinician before diagnosis.',
      data: record.resource
    });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
